#!/bin/bash
# System-Wide UI/UX Diagnosis - Command Reference
# pbsys May 27, 2026

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "SYSTEM-WIDE UI/UX DIAGNOSIS LOOP - COMMAND REFERENCE"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📋 THREE DIAGNOSTIC TOOLS"
echo ""
echo "1️⃣  FAST DEMO (20 seconds)"
echo "   $ node scripts/system-wide-diagnosis-demo.js"
echo "   Purpose: Quick validation of 4 public auth pages"
echo "   Status: ✅ 100% PASS"
echo ""
echo "2️⃣  FULL SYSTEM LOOP (2-minute intervals)"
echo "   $ node scripts/system-wide-diagnosis-loop.js"
echo "   Purpose: Continuous monitoring of all 22 pages"
echo "   Status: 🔄 RUNNING (PID: 3700)"
echo ""
echo "3️⃣  WATCHDOG (5-minute intervals, silent)"
echo "   $ node scripts/ui-ux-watchdog.js &"
echo "   Purpose: Background alerts-only monitoring"
echo "   Status: Available to start"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📊 VIEW RESULTS"
echo ""
echo "   Latest demo report:"
echo "   $ cat .hermes/regression-reports/demo-*.json | tail -1 | jq ."
echo ""
echo "   Latest system-wide report:"
echo "   $ ls -t .hermes/regression-reports/system-wide-*.json | head -1 | xargs cat | jq ."
echo ""
echo "   Loop output:"
echo "   $ tail -f .hermes/system-wide-diagnosis.log"
echo ""
echo "   Watchdog alerts:"
echo "   $ tail -f .hermes/ui-ux-alert.log"
echo ""
echo "   Screenshots:"
echo "   $ ls .hermes/regression-screenshots/ | head -10"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 USAGE PATTERNS"
echo ""
echo "   Pre-commit check:"
echo "   if node scripts/system-wide-diagnosis-demo.js; then git commit -m \"...\"; fi"
echo ""
echo "   Background monitoring:"
echo "   nohup node scripts/system-wide-diagnosis-loop.js >> .hermes/system-wide-diagnosis.log 2>&1 &"
echo ""
echo "   Watch progress:"
echo "   watch -n 5 'tail -5 .hermes/system-wide-diagnosis.log'"
echo ""
echo "   CI/CD integration:"
echo "   timeout 30 node scripts/system-wide-diagnosis-demo.js || exit 1"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📁 KEY FILES"
echo ""
echo "   Documentation:"
echo "   - .hermes/SYSTEM-WIDE-DIAGNOSIS-GUIDE.md (comprehensive guide)"
echo "   - .hermes/SYSTEM-WIDE-DIAGNOSIS-QUICK-REF.txt (quick reference)"
echo "   - .hermes/SYSTEM-WIDE-DEPLOYMENT-SUMMARY.txt (deployment summary)"
echo ""
echo "   Reports:"
echo "   - .hermes/regression-reports/demo-*.json (demo results)"
echo "   - .hermes/regression-reports/system-wide-*.json (full system results)"
echo "   - .hermes/regression-reports/loop-*.json (loop iteration results)"
echo ""
echo "   Screenshots:"
echo "   - .hermes/regression-screenshots/*.png (page captures)"
echo ""
echo "   Logs:"
echo "   - .hermes/system-wide-diagnosis.log (loop output)"
echo "   - .hermes/ui-ux-alert.log (watchdog alerts)"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ CHECKS PER PAGE"
echo ""
echo "   ✓ Bootstrap class detection (NEO V-TRACK only)"
echo "   ✓ Inline style audit (CSS variables allowed)"
echo "   ✓ Form label validation"
echo "   ✓ Button class compliance"
echo "   ✓ Heading structure (h1 required)"
echo "   ✓ ARIA attributes"
echo "   ✓ Color contrast ratios"
echo "   ✓ Responsive design (3 breakpoints)"
echo "   ✓ Performance metrics"
echo "   ✓ Screenshot capture"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📍 PAGES COVERED (22 Total)"
echo ""
echo "   Auth (4) ✅ VERIFIED:"
echo "   - /auth/login.php"
echo "   - /auth/register.php"
echo "   - /auth/forgot_password_smtp.php"
echo "   - /auth/reset_password_token.php"
echo ""
echo "   Admin (7) 🔧 READY:"
echo "   - /admin/dashboard.php"
echo "   - /admin/users/list.php & add.php"
echo "   - /admin/admins/list.php & add.php"
echo "   - /admin/bulk_import.php"
echo "   - /admin/reports.php"
echo ""
echo "   Vehicles (8) 🔧 READY:"
echo "   - /vehicles/{visitor,staff,student,contractor}/{list,add}.php"
echo ""
echo "   Search (2) 🔧 READY:"
echo "   - /search/admin_search.php"
echo "   - /search/user_search.php"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "✨ STATUS: 🟢 LIVE & MONITORING"
echo ""
echo "Latest Updates:"
echo "- Fast demo: 100% pass (4/4 auth pages)"
echo "- Full system loop: Running continuously"
echo "- All public pages standardized to NEO V-TRACK design"
echo "- 6 CSS utility classes added"
echo "- Full documentation complete"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
